### ISSUE TITLE
Not a usable commodity sensor

### ISSUE THREAD

**Issue by smith000-000** [wbyoung/watersmart#1]
So this creates a sensor with the proper device_class and unit_of_measurement but it doesn't have a state_class

I've created a nodered flow that adds the last state but if it misses an update for any reason I think it won't work. Is there a better way to get this into the energy dashboard?

**Comment by wbyoung** [comment]
I think we could add a `state_class` of `measurement` to either, but I'm not sure that would get it in the energy dashboard. I'm using it for a different reason, but seeing it in there could be nice.

The trouble is, this isn't the most reliable of data sources. I've gone 3 days before where it was still successfully obtaining data, but nothing new. I'm guessing this may be different per water utility, so it'd be interesting to hear your experience using it so far.

It may be better to configure a [_Utility Meter_ helper](https://www.home-assistant.io/integrations/utility_meter/) that uses one of these as an input source.

Maybe a new sensor with a `state_class` of `total` could be added to this project, `sensor.watersmart_<host>_usage`. I haven't spent much time with the energy dashboard, so I don't know if that would get it in there or not.

**Comment by wbyoung** [comment]
> I think we could add a `state_class` of `measurement` to either, but I'm not sure that would get it in the energy dashboard. I'm using it for a different reason, but seeing it in there could be nice.

Nope, that's not possible. Here's the error that produces:

> Entity sensor.watersmart_test_gallons_for_most_recent_full_day (<class 'custom_components.watersmart.sensor.WaterSmartSensor'>) is using state class 'measurement' which is impossible considering device class ('water') it is using; expected None or one of 'total_increasing', 'total'

**Comment by wbyoung** [comment]
> Maybe a new sensor with a `state_class` of `total` could be added to this project, `sensor.watersmart_<host>_usage`.

I spent a little time just now looking into this. My first thought was just to update an sensor that starts counting at zero with each update that is pulled. I don't see any examples of this happening in the Home Assistant Core components. That doesn't mean it's not possible, but just that it's not really the ideal way of setting up an integration.

I also realized that it would probably be better if this were an actual total used for the lifetime of your account. Logging back into my account, I can't tell how far back usage can be queried, but it appears they only show 5 years in the interface in certain places. Also, this would mean making a call to another (undocumented) endpoint & maintaining that sensor if the call changes as well.

For now, I think the best approach is to leave things as they are and work to figure out how to get a nice configuration that we can share in the `README` for how to get it in the energy dashboard.

**Comment by wbyoung** [comment]
I've added a helper to see how far it get me:

<img width="571" alt="Screenshot 2024-09-07 at 6 59 55 AM" src="https://github.com/user-attachments/assets/8a7e357d-7ce4-4bcd-9bd4-8f2091d1f9ae">

**Comment by smith000-000** [comment]
Yeah it's not very reliable. There's obviously latency between usage updates to their API. 

My municipality just switched to watersmart but it appears they have history back until November.  

And I didn't even know the helper was there. It does the same thing as the first nodered flow I made except it works. 

Is your code generating that historical information in the yaml or is that homeassistant?
![image](https://github.com/user-attachments/assets/a5ef3cdf-60ac-48a0-a148-6dca39c1fb45)

**Comment by wbyoung** [comment]
I added that historical information before adding the action (previously called service) call. I needed the historic data for what I'm using it for. In theory, they could be removed now in favor of the action call. I may eventually deprecate it (especially if the project becomes more popular).

Let me know how the helper works for you, and if it works well, then maybe a documentation change would be sufficient to fix this issue for you. 😊
